### ISSUE TITLE
Create a testing plan for our repo.

### ISSUE THREAD

**Issue by shivamvats** [AGV-IIT-KGP/eklavya-2015#58]
cc @hargup @abinashmeher999 @kumarkrishna @krishna95 

## ToDo

- [ ] Choose a testing strategy
- [ ] Write a debug mode for the code with nice stacktraces
- [ ] Choose a testing framework
